version: '2'

services:
  fmysql:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./db-dump:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: host
#    ports:
#      - "3306:3306"

  fphpmyadmin:
    depends_on:
      - fmysql
    image: phpmyadmin/phpmyadmin
    links:
      - fmysql
    restart: always
    environment:
      PMA_HOST: fmysql
      PMA_PORT: 3306
    ports:
      - "89:80"

  fapache2:
    depends_on:
      - fmysql
    build: ./apache/
    links:
      - fmysql
    restart: always
    ports:
      - "88:80"
    volumes:
      - ./apache/conf:/etc/apache2/sites-available/
      - ../www:/var/www
      - ../log/apache2:/var/log/apache2
      - ../tmp:/tmp

  fnginx:
    build: ./nginx/
    ports:
        - "87:80"
    links:
      - fapache2
      - fmysql
      - fphpmyadmin
    restart: always
    volumes:
      - ./nginx/config:/etc/nginx/sites-enabled/
      - ../log/nginx:/var/log/nginx
      - /var/www:/var/www

volumes:
    db_data:
